# Generated by Django 5.2.6 on 2025-09-13 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id_colaborador', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=45)),
                ('cpf', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='EPI',
            fields=[
                ('id_epi', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=45)),
                ('quantidade', models.IntegerField()),
                ('maximo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id_equipamento', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=90)),
                ('situacao', models.IntegerField()),
                ('condicao', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Consumo',
            fields=[
                ('id_consumo', models.AutoField(primary_key=True, serialize=False)),
                ('data_consumo', models.DateTimeField()),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.colaborador')),
            ],
        ),
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id_emprestimo', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.DateTimeField()),
                ('data_devolucao', models.DateTimeField()),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.colaborador')),
            ],
        ),
        migrations.CreateModel(
            name='Consumo_EPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.consumo')),
                ('epi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.epi')),
            ],
            options={
                'unique_together': {('consumo', 'epi')},
            },
        ),
        migrations.CreateModel(
            name='Itens_Emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emprestimo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.emprestimo')),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.equipamento')),
            ],
            options={
                'unique_together': {('equipamento', 'emprestimo')},
            },
        ),
    ]
